version: '3'
services:
  web:
    build: .
    ports:
    -  "8080:8080"
  db:
    build:
      context: .
      dockerfile: postgres.Dockerfile
    restart: always
    image: postgres
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: p2pdinner